-- MySQL Script generated by MySQL Workbench
-- Thu May 28 12:19:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bargylus_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bargylus_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bargylus_db` DEFAULT CHARACTER SET utf8 ;
USE `bargylus_db` ;

-- -----------------------------------------------------
-- Table `bargylus_db`.`Grapes_Varieties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bargylus_db`.`Grapes_Varieties` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `name` (`name` ASC) ,
  UNIQUE INDEX `name_2` (`name` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bargylus_db`.`ModesOfPayments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bargylus_db`.`ModesOfPayments` (
  `Id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `name` (`name` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bargylus_db`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bargylus_db`.`Users` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `registrationDate` DATE NULL DEFAULT NULL,
  `birthDate` DATE NOT NULL,
  `streetHome` VARCHAR(45) NOT NULL,
  `zip` INT(11) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `canton` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `email` (`email` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bargylus_db`.`Wines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bargylus_db`.`Wines` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `year` INT(11) NOT NULL,
  `alcohol` FLOAT NOT NULL,
  `basicPrice` FLOAT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `size` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `year` (`year` ASC, `name` ASC, `size` ASC) ,
  UNIQUE INDEX `year_2` (`year` ASC, `name` ASC, `size` ASC) ,
  UNIQUE INDEX `year_UNIQUE` (`year` ASC) ,
  UNIQUE INDEX `size_UNIQUE` (`size` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bargylus_db`.`Users_buy_Wines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bargylus_db`.`Users_buy_Wines` (
  `Id` INT(11) NOT NULL,
  `Users_Id` INT(11) NULL DEFAULT NULL,
  `Wines_Id` INT(11) NULL DEFAULT NULL,
  `ModesOfPayments_Id` INT(11) NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Users_has_Wines_Wines1_idx` (`Wines_Id` ASC) ,
  INDEX `fk_Users_has_Wines_Users1_idx` (`Users_Id` ASC) ,
  INDEX `fk_Users_buy_Wines_ModesOfPayments1_idx` (`ModesOfPayments_Id` ASC) ,
  CONSTRAINT `fk_Users_buy_Wines_ModesOfPayments1`
    FOREIGN KEY (`ModesOfPayments_Id`)
    REFERENCES `bargylus_db`.`ModesOfPayments` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Wines_Users1`
    FOREIGN KEY (`Users_Id`)
    REFERENCES `bargylus_db`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Wines_Wines1`
    FOREIGN KEY (`Wines_Id`)
    REFERENCES `bargylus_db`.`Wines` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bargylus_db`.`Users_choose_ModesOfPayments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bargylus_db`.`Users_choose_ModesOfPayments` (
  `Id` INT(11) NOT NULL,
  `Users_Id` INT(11) NOT NULL,
  `ModesOfPayments_Id` INT(11) NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Users_has_ModesOfPayments_ModesOfPayments1_idx` (`ModesOfPayments_Id` ASC) ,
  INDEX `fk_Users_has_ModesOfPayments_Users_idx` (`Users_Id` ASC) ,
  CONSTRAINT `fk_Users_has_ModesOfPayments_ModesOfPayments1`
    FOREIGN KEY (`ModesOfPayments_Id`)
    REFERENCES `bargylus_db`.`ModesOfPayments` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_ModesOfPayments_Users`
    FOREIGN KEY (`Users_Id`)
    REFERENCES `bargylus_db`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bargylus_db`.`Wines_compose_Grapes_Varieties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bargylus_db`.`Wines_compose_Grapes_Varieties` (
  `Id` INT(11) NOT NULL,
  `Wines_Id` INT(11) NOT NULL,
  `Grapes_Varieties_Id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Wines_has_Grapes_Varieties_Grapes_Varieties1_idx` (`Grapes_Varieties_Id` ASC) ,
  INDEX `fk_Wines_has_Grapes_Varieties_Wines1_idx` (`Wines_Id` ASC) ,
  CONSTRAINT `fk_Wines_has_Grapes_Varieties_Grapes_Varieties1`
    FOREIGN KEY (`Grapes_Varieties_Id`)
    REFERENCES `bargylus_db`.`Grapes_Varieties` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Wines_has_Grapes_Varieties_Wines1`
    FOREIGN KEY (`Wines_Id`)
    REFERENCES `bargylus_db`.`Wines` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
